name: Terraform CI for Staging

on:
    pull_request:
      branches:
        - main
  
  env:
    TF_CLOUD_ORGANIZATION: "mwong-tamu"
    TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
    env_name: ${{ github.ref_name == 'main' && 'staging' || github.ref_name }}
    TF_WORKSPACE: "learn-terraform-github-actions"
    CONFIG_DIRECTORY: "./"

jobs:
  terraform:
    name: Terraform Plan & Apply for Staging
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Initialize
        run: terraform init

      - name: Terraform Plan using staging.tfvars
        run: terraform plan -var-file=staging.tfvars

      - name: Terraform Apply using staging.tfvars
        if: github.ref == 'refs/heads/main' # Only apply on main branch
        run: terraform apply -var-file=staging.tfvars -auto-approve